apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-lzao
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0058-tenant/tkrw-pr712-0075-0058-app/devfile-sample-lzao@sha256:39a93feae7f743bf0f26621ad518675bd6f95f09f39cfe58c08349209bfe37ac
        name: my-nodejs
        resources: {}
status: {}
